### ISSUE TITLE
CH VACD Other Relevant Observations: add short explanation about the resource type Condition

### ISSUE THREAD

**Issue by vnf1** [hl7ch/ch-vacd#101]
The profile [CH VACD Other Relevant Observations ](http://build.fhir.org/ig/hl7ch/ch-vacd/StructureDefinition-ch-vacd-other-observations.html) does not derive from Observation, as the name would suggest, but from Condition. This is due to the fact that the name has been taken over from CDA and in STU 1 it was decide to change the underlaying resource from Observation to Condition.

A short explanation would help understand the naming mismatch ;-)

**Comment by ralych** [comment]
this is obsolete since the profile is deleted
