### ISSUE TITLE
CH VACD Medication For Immunization Profile (Oliver Egger, ahdis)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#104]
ch.fhir.ig.ch-vacd#2.0.0 /StructureDefinition-ch-vacd-medication-for-immunization.html

Could CH VACD Medication be derived from CH EMED Vaccination? Discussion coming up because It looks currently that there is a difference:
- In CH-EMED Medications a coding should be provided with a GTIN (see profile, e.g: http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-medication.html, example)
- In CH-VACD Medication example the GTIN is provided in the identifier and the coding is used differently (see example were identifier is gln and coding is 106181007 Immunologic substance (substance),
 the profile does not explicitly say something about mapping of identifier/coding).

Oliver Egger, ahdis

**Comment by ziegm** [comment]
Review done, please adapt the version of CH EMED (see [here](https://github.com/hl7ch/ch-vacd/commit/06fab8115b21a17c21988e1830dbeb53b055b140#commitcomment-76782583)) and then it is okay.

**Comment by ziegm** [comment]
Review done, thanks for updating
