### ISSUE TITLE
CH VACD Recommendation Patient Profile - reduce restriction for name (Roeland Luykx (in name of HCI))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#107]
ch.fhir.ig.ch-vacd#2.0.0 /StructureDefinition-ch-vacd-recommendation-patient.html

The restrictions for the patient profile are to extreme. i.e. CDS systems should bake reports (PDF) with recommendation contents (- seems to belong under CE restrictions) and have to include the patients name.
The pseudonymization should be not as restricted as it is. It will depend on different use cases for CDS systems.
To have an usable exchange format the defined restrictions have to be reduced.

Roeland Luykx (in name of HCI)

**Comment by annatinafoppa** [comment]
ok, has connection to https://github.com/hl7ch/ch-vacd/issues/124
