### ISSUE TITLE
Provide Minimal Data Set or Must Support (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#110]
ch.fhir.ig.ch-vacd#2.0.0 /

Feedback from vendors trying to map to this IG: quick overview is needed; which fields belong to Minimal data set. Could be marked by Must-support flags as with eMedication

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
This is a question of understanding Implementation guides and the relations.
A case to vendors to look for educatinal courses on implementation guides and profiling.

**Comment by ralych** [comment]
Must support is the wrong element to guide this.

**Comment by ralych** [comment]
@annatinafoppa Please give me feedback about the settings done.

**Comment by pjolo** [comment]
@ralych Must Support selection from eHealth Suisse:
[220623_Impfen_MustSupport.docx](https://github.com/hl7ch/ch-vacd/files/8965666/220623_Impfen_MustSupport.docx)

**Comment by annatinafoppa** [comment]
It's not totally aligned with the document provided, but should be a good basis for the Projectathon and the ballot. Thanks
