### ISSUE TITLE
absent or unknown immunization leads to unlogic constraints -- CH VACD Immunization Profile (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#111]
ch.fhir.ig.ch-vacd#2.0.0 /StructureDefinition-ch-vacd-immunization.html

If you fill in that there are no known immunization (immunization.vaccinecode.slices) , the profile still forces you to enter the occurence date or dose which makes no sense. has to be placed elsewhere

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
if there is no immunization done -> no date exists.
so there does not have to be added an immuization resource!
its logic!

**Comment by annatinafoppa** [comment]
but then why would you need this value set anyway? http://hl7.org/fhir/uv/ips/STU1/ValueSet-absent-or-unknown-immunizations-uv-ips.html . i think the reason is that you want to indicate that there are no immunizations present which is a different information than no indication at all

**Comment by ralych** [comment]
@annatinafoppa analyzing the profile i detected that the cardinality of doseNumber and occurence is set to 1..1 in the resource http://hl7.org/fhir/R4/immunization.html.
occurence can always be set to the date where this entry is done - even if no immunization is done
doseNumber has to be set as soon a protocolApplied item is defined, but it can be set to 0.

could this be a suitable solution?

**Comment by annatinafoppa** [comment]
Yes, that sounds viable. let's gain some experience when the format is implemented and see how it works. I'll close this issue therefore.
