### ISSUE TITLE
Specify presentation requirements of Immunization Administration Document (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#112]
ch.fhir.ig.ch-vacd#2.0.0 /immunization-administration-document.html

Add stylesheet and requirements about narrative content in order that the structured document can be understood by human readers

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
readme has  to be completed with more explanations

**Comment by annatinafoppa** [comment]
shouldn't it be mentioned in the profile somewhere? please check

**Comment by annatinafoppa** [comment]
ok
