### ISSUE TITLE
additional concept "Anaphylaxis caused by component of vaccine product (disorder)" ch-vacd-immunization-allergyintolerances-vs (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#113]
ch.fhir.ig.ch-vacd#2.0.0 /ValueSet-ch-vacd-immunization-allergyintolerances-vs.html

Please add concept:

1217476001 Anaphylaxis caused by component of vaccine product (disorder)

 SNOMED international followed our change request to introduce this concept

Annatina Foppa, eHealth Suisse

**Comment by annatinafoppa** [comment]
Covered by https://github.com/hl7ch/ch-vacd/issues/126
