### ISSUE TITLE
Change English display name to "Rotavirus disease" ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#114]
ch.fhir.ig.ch-vacd#2.0.0 /ValueSet-ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs.html

English display of 18624000	Disease caused by Rotavirus => change to "Rotavirus disease"; synonym was accepted by SNOMED international. more suitable than the other expression

Annatina Foppa, eHealth Suisse

**Comment by annatinafoppa** [comment]
Covered by https://github.com/hl7ch/ch-vacd/issues/126
