### ISSUE TITLE
additional HPV vaccine ch-vacd-vaccines-snomedct-vs (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#115]
ch.fhir.ig.ch-vacd#2.0.0 /ValueSet-ch-vacd-vaccines-snomedct-vs.html

Please add -	«1209197008 |Vaccine product containing only Human papillomavirus 6, 11, 16, 18, 31, 33, 45, 52 and 58 antigens (medicinal product)|»

Annatina Foppa, eHealth Suisse

**Comment by annatinafoppa** [comment]
Covered by https://github.com/hl7ch/ch-vacd/issues/126
