### ISSUE TITLE
additional HPV-vaccination ch-vacd-ch-vaccination-plan-immunizations-vs (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#116]
ch.fhir.ig.ch-vacd#2.0.0 /ValueSet-ch-vacd-ch-vaccination-plan-immunizations-vs.html

Please add -	1209198003 | Administration of vaccine product containing only Human papillomavirus 6, 11, 16, 18, 31, 33, 45, 52 and 58 antigen (procedure) |

Annatina Foppa, eHealth Suisse

**Comment by annatinafoppa** [comment]
covered by https://github.com/hl7ch/ch-vacd/issues/126
