### ISSUE TITLE
map or remove ATC value set -- ch-vacd-vaccines-atc-vs (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#119]
ch.fhir.ig.ch-vacd#2.0.0 /ValueSet-ch-vacd-vaccines-atc-vs.html

ATC value set is provided as alternative to the Swissmedic Codes and the SNOMED codes, but there is no mapping of ATC to these other values. Should we introduce it or can we drop the ATC vs because SNOMED and Swissmedic cover it all?

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
let Valueset in IG, but remove from slice.
futher work in backlog.

**Comment by annatinafoppa** [comment]
that's fine. FYI: for the first release of the vaccine module we will work with value set Swissmedic only
