### ISSUE TITLE
Profile Definition for "Basic Immunization done"

### ISSUE THREAD

**Issue by ralych** [hl7ch/ch-vacd#121]
To declare a basic immunization don i.e. DTPa or Polio an additional profile has to be defined.

**Comment by annatinafoppa** [comment]
@ralych Meiner Meinung nach müsste es beim dazugehörigen Value-Set auf Französisch statt "Avoir reçu ..." heissen: "A reçu ...". Vgl. http://build.fhir.org/ig/hl7ch/ch-vacd/ValueSet-ch-vacd-basic-immunization-vs.html .
du kannst das überprüfen und das Issue danach selbst schliessen
