### ISSUE TITLE
Improve Slicing that info entry[1] warnings are not shown

### ISSUE THREAD

**Issue by oliveregger** [hl7ch/ch-vacd#125]
IPS did this, that they added the potential slices to the bundle.entries:
https://build.fhir.org/ig/HL7/fhir-ips/StructureDefinition-Bundle-uv-ips.html

![image001](https://user-images.githubusercontent.com/2414516/172660832-5b59c261-1777-4243-aa0e-e9a4f96aac48.png)
6

**Comment by ziegm** [comment]
Review: see [comment](https://github.com/hl7ch/ch-vacd/commit/1986fd81aaca18e369fc6dd28ed2b7756ea5a0ee#commitcomment-76783920)

**Comment by ziegm** [comment]
review done, okay now
