### ISSUE TITLE
Add Note information to Testdata

### ISSUE THREAD

**Issue by ralych** [hl7ch/ch-vacd#133]
1.      Wir werden die Kommentare zu Impfungen und Vorerkrankungen im Feld «note» der Immunization bzw. PastIllness Ressource nutzen, insbesondere mit Referenz auf Originaleinträge, wenn die Kommentare nachträglich erfasst werden. Dazu fehlen aktuell Beispiele. Kannst du bitte Beispiele dazu ins IG mit aufnehmen?     

2.      Für das Testen ist es unpraktisch, dass die referenzierten GFP keine gebräuchlichen Namen und Adressen haben. Daher schlage ich eine Umbenennung wie folgt vor:

TC_HCP1_C1:
Name: «Müller»
Vorname: «Peter»
Strasse: «Grabenstrasse 2»
Ort: «Zürich»
PLZ: «8005»

TC_HCP2_C2:
Name: «Meier»
Vorname: «Gabriela»
Strasse: «Werthgasse 34»
Ort: «Bern»
PLZ: «3000»

**Comment by msmock** [comment]
Elemente des Impfausweises im EPD sollen kommentiert werden können. Dazu soll das "note" element der [CH VACD Immunization](https://fhir.ch/ig/ch-vacd/StructureDefinition-ch-vacd-immunization.html), [CH VACD Past Illness](https://fhir.ch/ig/ch-vacd/StructureDefinition-ch-vacd-pastillnesses.html), [CH VACD AllergyIntolerance](https://fhir.ch/ig/ch-vacd/StructureDefinition-ch-vacd-allergyintolerances.html), etc. genutzt werden. 

Im EPD gibt es dann 2 zu unterscheidende Fälle: 

1. Eine Impfung, Allergie, Vorerkrankung, etc. wird mit einem Kommentar erfasst. 
2. Zu einer Impfung, Allergie, Vorerkrankung, etc. wird nachträglich ein Kommentar erfasst. 

In Fall 2. wird im EPD jeweils ein neues Dokument für die Impfung, Allergie, Vorerkrankung, etc. mit einer Referenz   auf das Original (Impfung, Allergie, Vorerkrankung, etc.) gespeichert. 

Für die Implementierung benötigen wir Testfiles für Fall 1 sowie Testcases für Fall 2.

**Comment by ralych** [comment]
New TestCases http://build.fhir.org/ig/hl7ch/ch-vacd/TestCases.html#f-add-notes-to-existing-elements

**Comment by pjolo** [comment]
@ralych 
Please correct the sentence at "note" from:

Der Patient hat diese Impfung ohne jedwelcher nebenwirkungen gut vertragen.
to
Der Patient hat diese Impfung ohne **jegliche Nebenwirkungen** gut vertragen.

**Comment by pjolo** [comment]
Ok and issue closed
