### ISSUE TITLE
Reconsiliation Swissmedic List Vaccines

### ISSUE THREAD

**Issue by ralych** [hl7ch/ch-vacd#134]
See [Listen und Verzeichnisse](https://www.swissmedic.ch/swissmedic/de/home/services/listen_neu.html)

**Comment by ralych** [comment]
[SwissMedic_Zugelassene_Impfstoffe_Blutprodukte_20220831_v2.xlsx](https://github.com/hl7ch/ch-vacd/files/9476501/SwissMedic_Zugelassene_Impfstoffe_Blutprodukte_20220831_v2.xlsx)

**Comment by ralych** [comment]
[SwissMedic_Zugelassene_Impfstoffe_Blutprodukte_20221031.xlsx](https://github.com/hl7ch/ch-vacd/files/9926046/SwissMedic_Zugelassene_Impfstoffe_Blutprodukte_20221031.xlsx)

**Comment by pjolo** [comment]
Reviewed and ok
