### ISSUE TITLE
Gap CH VACD aus dem KSA

### ISSUE THREAD

**Issue by ralych** [hl7ch/ch-vacd#135]
Feedback KSA Vaccines

**Comment by ralych** [comment]
[ratschiller_KSA_impfstoffe.pdf](https://github.com/hl7ch/ch-vacd/files/9476499/ratschiller_KSA_impfstoffe.pdf)

**Comment by ralych** [comment]
check for values in swiss medic list. see
[ratschiller_KSA_impfstoffe_v3.pdf](https://github.com/hl7ch/ch-vacd/files/9927386/ratschiller_KSA_impfstoffe_v3.pdf)
for result

**Comment by ralych** [comment]
valueset/codesystem can be seen under http://build.fhir.org/ig/hl7ch/ch-vacd/branches/stu3-ballot_resolution/index.html

**Comment by pjolo** [comment]
Reviewed and ok
