### ISSUE TITLE
Rename Vs or explain clearer ch-vacd-basic-immunization-vs (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#136]
ch.fhir.ig.ch-vacd#2.1.0 /ValueSet-ch-vacd-basic-immunization-vs.html

the name "basic-immunization" was confusing to some implementers because they expected it to cover all "Basisimpfungen" and not only DTP and Polio. see with health professional what suits better

Annatina Foppa, eHealth Suisse

**Comment by msmock** [comment]
We should also improve the description of the "basic-immunization", in fact I can't see the use of the separate collection at all. If only specific vaccinations are to be stored in that collection, a restriction must be added. (In the current implementation of the vaccination module we just don't know how to handle "basic-immunization" collections)

**Comment by pjolo** [comment]
Reviewed and ok
