### ISSUE TITLE
Detailed description for the representation via stylesheet (Patrick Jolo, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#137]
ch.fhir.ig.ch-vacd#2.1.0 /immunization-administration-document.html

For the CH-VACD exchange format, the representation of discrete data can also be done using a stylesheet. The implementation guide was missing a description of how this representation should be done.

Patrick Jolo, eHealth Suisse

**Comment by ralych** [comment]
@pjolo do you mean the generation of narrative text using xsl transformation or do you mean the possibility to add a CSS reference to the composition?

**Comment by pjolo** [comment]
It is good for me if a sample document is implemented as described in Issue [#138](https://github.com/hl7ch/ch-vacd/issues/138).
