### ISSUE TITLE
Home: Influence IPS (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#139]
ch.fhir.ig.ch-vacd#2.1.0 /

"The circumstance to be able to exchange the information across borders had his influence on the specification. The International Patient Summary Implementation Guide (IPS) gave some support."

Could this be explained in more detail?

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
It's clearer now, thanks

**Comment by pjolo** [comment]
Reviewed and ok
