### ISSUE TITLE
Use Cases: Formatting (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#140]
These are just small formatting suggestions for the use cases:
* Adjust header formatting so that the same level does not appear twice (here e.g. 32).
![image](https://user-images.githubusercontent.com/32767151/189479131-13e1d5ce-081d-425f-8951-f58b04b063fd.png)
* Some diagrams are very small (font), use whole page width.

Michaela Ziegler, ahdis ag

**Comment by ralych** [comment]
see http://build.fhir.org/ig/hl7ch/ch-vacd/branches/stu3-ballot_resolution/usecases.html

**Comment by ziegm** [comment]
Looks much better now :-)

**Comment by pjolo** [comment]
Reviewed and ok
