### ISSUE TITLE
CH VACD Immunization (Juerg Bleuer, Healthevidence GmbH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#141]
ch.fhir.ig.ch-vacd#2.1.0 /StructureDefinition-ch-vacd-immunization.html

 occurrenceString has apparently been kicked out of CH VACD Immunisation. 

e.g. in my children's vaccination card there are entries like: DiTePE: 3 doses in the first 6 months.

    If you don't have occurrenceString, you have to enter a fake date.
Please change that: occurrenceString must be there in order to cover use cases like the one stated. above.

Juerg Bleuer, Healthevidence GmbH

**Comment by ralych** [comment]
@JBleuer can we resolve this negative comment by answering to look at the profile [CH VACD Basic Immunization](http://build.fhir.org/ig/hl7ch/ch-vacd/branches/stu3-ballot_resolution/StructureDefinition-ch-vacd-basic-immunization.html)?
The ValueSet can be extended by having other cases with basic immunization. The two values came from the EKIF vaccination plan.

**Comment by ralych** [comment]
After resolving the negative comment with the proposed solution as discussed with @JBleuer this can be closed.
