### ISSUE TITLE
UUID for Immunization Administration document and Vaccination Record Document (Patrick Jolo (eHealth Suisse))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#142]
ch.fhir.ig.ch-vacd#2.1.0 /vaccination-record-document.html

For "Immunization Administration document" and "Vaccination Record Document" only the UUID should be required at the "section" and "entry" level. The reason for this requirement is that the immunization module only uses the UUID for the summary of immunization-relevant records and for the replacement of immunizations, and so on. 

Patrick Jolo (eHealth Suisse)

**Comment by ralych** [comment]
@pjolo in normal cases it will be done like this. in the IG there where names choosen for better reading. this is an automatism of the fsh/publisher. so not complete realistic....

**Comment by ralych** [comment]
@pjolo the format of the id to be restricted to UUID is not the right way, but UUID's ar the normal case.

**Comment by pjolo** [comment]
From my side, the issue can be closed. Nothing needs to be done about this issue.
