### ISSUE TITLE
FR- und IT-Übersetzungen falsch ch-vacd-entry-conflict-vs (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#143]
ch.fhir.ig.ch-vacd#2.1.0 /ValueSet-ch-vacd-entry-conflict-vs.html

Auf Französisch und Italienisch stehen Verben statt ein Nomen. Französisch korrekt wäre "Doublon", für Italienisch müsst ihr Übersetzer fragen

Annatina Foppa, eHealth Suisse

**Comment by pjolo** [comment]
Reviewed and ok
