### ISSUE TITLE
Archive ch-vacd-recommendation-forecast-status-vs (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#144]
ch.fhir.ig.ch-vacd#2.1.0 /ValueSet-ch-vacd-recommendation-forecast-status-vs.html

No system is using this. Archive respectively delete for next version (still findable in his version)

Annatina Foppa, eHealth Suisse

**Comment by pjolo** [comment]
Reviewed and ok
