### ISSUE TITLE
Archive ch-vacd-vaccines-atc-vs (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#145]
ch.fhir.ig.ch-vacd#2.1.0 /ValueSet-ch-vacd-vaccines-atc-vs.html

No system is using this. Archive respectively delete for next version (still findable in his version). The Mapping can be done at a later point when IPS is introduced in Switzerland. Value Sets of IPS are outdated

Annatina Foppa, eHealth Suisse

**Comment by pjolo** [comment]
Reviewed and ok
