### ISSUE TITLE
Terminology -- Mapping zwischen SwissMedic und Snomed VS erstellen? (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#146]
ch.fhir.ig.ch-vacd#2.1.0 /terminology.html

abklären, ob relevant oder ob Weg via TargetDisease hinreichend ist

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
This is done
