### ISSUE TITLE
relatesTo reference in Test Cases 

### ISSUE THREAD

**Issue by msmock** [hl7ch/ch-vacd#147]
The relatesTo element in Immunization Administration Composition in the correction use case contains parts of the fullUrl but should reference the UUID in the Identifier of the Immunization Administration Composition of the Immunization Administration Document which is corrected or overridden. The test case files shall be updated to reference the UUID in the relatesTo attribute.

**Comment by ralych** [comment]
Change to UUID use is possible. makes the reading/searching of the IG more complicated.

**Comment by ralych** [comment]
In accordance with @pjolo this will not be changed using UUID's as id in the test cases.
