### ISSUE TITLE
Swiss Complication Risks Codesystem (Marcel Hanselmann, HL7)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#148]
ch.fhir.ig.ch-vacd#2.1.0 /CodeSystem-ch-vacd-complication-risks-cs.html

Es wundert mich, dass man sich die Mühe genommen hat, eine Schweizerische Liste mit den Risiken von Impfkomplikationen aufzustellen, die Risiko-Konditionen sind doch wohl eher international. Ausserdem hat man dann ja doch das Gefühl, dass ein solches Value Set nicht alle Instanzen abdeckt. Die Konditionen liessen sich ja leicht mit ICD-11 oder SNOMED CT codieren. Eine wichtige Impfkomplikation sind anaphylaktische Reaktionen, die aber im Value-Set fehlen. 
Vorschlag: Schweizerische Liste wegwerfen, dafür ICD-11 verwenden.

Marcel Hanselmann, HL7

**Comment by ralych** [comment]
dupplicate of https://github.com/hl7ch/ch-vacd/issues/52
