### ISSUE TITLE
Swiss Exposure Risks Codesystem (Marcel Hanselmann HL7)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#149]
ch.fhir.ig.ch-vacd#2.1.0 /CodeSystem-ch-vacd-exposure-risks-cs.html

Hier habe ich den gleichen Einwand wie beim Value Set Swiss Complication Risks Value Set.   Situationen, Berufe, Vorlieben, sexuelle Orientierungen etc., die ein erhöhtes Expositionsrisiko mit sich bringen, gibt es zu Hauf, und sind abhängig vom Übertragungsweg. Und warum trifft es gerade der Fledermausforscher, und nicht, was viel häufiger ist, den Katzenliebhaber oder Hundefreund, nicht zu reden von all den Ornithosen der Vogelfreunde. Und warum die Rekruten, überall wo viel Menschen zusammenkommen, besteht dann ein erhöhtes Risiko. Ich weiss, dass solche Überlegungen bei der Indikation zu den Impfungen eine gewisse Rolle spielen, z.B. bei Impfstoffmangel. Geht da nicht einfach ein Freitext Feld, statt einer Codierung?

Marcel Hanselmann HL7

**Comment by ralych** [comment]
dupplicate of #52
