### ISSUE TITLE
romansh translation of value sets in use

### ISSUE THREAD

**Issue by annatinafoppa** [hl7ch/ch-vacd#151]
if eSanita is going to introduce the vaccination into their EPR, they also need romansh translation. please provide translation for relevant value sets.

**Comment by ralych** [comment]
@pjolo can you look for translation options to have the valuesets translated in "Rumantsch"

**Comment by pjolo** [comment]
In the excel, the relevant ValueSets are translated into Romansh.
[230125_ValueSetsImpfung_Romansh.xlsx](https://github.com/hl7ch/ch-vacd/files/10510537/230125_ValueSetsImpfung_Romansh.xlsx)

**Comment by pjolo** [comment]
Romansch translations added:
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-vaccines-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-vaccines-snomedct-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-immunization-allergyintolerances-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-basic-immunization-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-laboratory-serology-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-recommendation-categories-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-risks-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-ch-vaccination-plan-immunizations-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-route-of-administration-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-entry-conflict-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-basic-immunization-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-swissmedic-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-recommendation-forecast-status-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-entry-conflict-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-exposure-risks-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-myvaccines-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-complication-risks-cs.html

Pull request:
* https://github.com/hl7ch/ch-vacd/pull/166

**Comment by pjolo** [comment]
Romansh translation added:
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-vaccines-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-immunization-allergyintolerances-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-basic-immunization-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-laboratory-serology-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-recommendation-categories-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-risks-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-ch-vaccination-plan-immunizations-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-route-of-administration-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/ValueSet-ch-vacd-entry-conflict-vs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-basic-immunization-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-swissmedic-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-complication-risks-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-myvaccines-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-recommendation-forecast-status-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-entry-conflict-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-clinical-decision-support-event-cs.html
* http://build.fhir.org/ig/hl7ch/ch-vacd/branches/pjolo_valueSet_translations/CodeSystem-ch-vacd-exposure-risks-cs.html

Pull request:
* https://github.com/hl7ch/ch-vacd/pull/166
