### ISSUE TITLE
Immunization Recommendation Request Message: Patientendaten pseudonymisieren  (Emmanuel Eschmann (CISTEC AG))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#152]
ch.fhir.ig.ch-vacd#2.1.0 /immunization-recommendation-request-message.html

Der Einführungstext zur "Immunization Recommendation Request Message" erwähnt zwar, dass "The patient data MUST be pseudonymized.", das entsprechende Bundle "CH VACD Message Immunization Recommendation Request" verwendet dann aber als Bundle-Entry zum Patienten (in http://fhir.ch/ig/ch-vacd/StructureDefinition-ch-vacd-recommendation-request-message-definitions.html#Bundle.entry:Patient) eine Ressource vom Typ CHCorePatient. Diese erlaubt die Eingabe von vollständigen Angaben zum Patienten (Vornamen, Familiennamen, Geburtsdatum, Adresse, …).
Mindestens müsste im Freitext des Einführungstextes aufgeführt werden, welche Patientendaten überhaupt vom Recommendation-System verwendet werden (z.B. Geschlecht, Wohnkanton, Alterskategorien inkl. Grenzen (z.B. 0-12Mt, 1-6 J, …. > 90J)), um keine überflüssigen Daten zu senden, die nicht benötigt werden und Rückschluss auf den Patienten erlauben könnten.
Idealer wäre, wenn das Bundle "CH VACD Message Immunization Recommendation Request" eine Bundle-Entry zum Patienten beinhaltet, die ein spezifisches Patienten-Profil aufweist, welches ausschliesslich die vom Recommendation-System benötigten Angaben zulässt.

Emmanuel Eschmann (CISTEC AG)

**Comment by ralych** [comment]
Der text "The patient data MUST be pseudonymized." wur de vergessen zu löschen, nachdem wir alle entsprechenden profile die genau diese pseudonymisierung umgesetzt haben entfernt haben.
Wieso das?: wir haben bei der realisation eines entsprechenden CDS systems und konsultation der medizinproduktanforderungen beschlossen, die pseudonymisierung liess es nicht zu dass das CDS system entsprechende empfehlungen ohne name usw herausgeben kann, dies aber gefordert ist für medizinprodukte (darstellung der resultate gehört dazu).
schützen der daten sollte an anderer stelle gelöst werden.

**Comment by ralych** [comment]
the corrected text can be seen under [stu3-ballot_resolution](https://github.com/hl7ch/ch-vacd/tree/stu3-ballot_resolution)

**Comment by EmmanuelEschmann** [comment]
oK - meine Rückmeldung erübrigt sich durch das Entfernen des Textes "The patient data MUST be pseudonymized."

PS: Im neuen Text "inkluding" mit "c" schreiben.

**Comment by pjolo** [comment]
Reviewed and ok
