### ISSUE TITLE
include HTML fragments

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-vacd#155]
New requirements for IG:

<html>
<body>

1 | warning | The HTML fragment 'ip-statements.xhtml' is not included anywhere in the produced implementation guide
-- | -- | --
2 | warning | The HTML fragment 'cross-version-analysis.xhtml' is not included anywhere in the produced implementation guide
3 | warning | The HTML fragment 'dependency-table.xhtml' is not included anywhere in the produced implementation guide
4 | warning | The HTML fragment 'globals-table.xhtml' is not included anywhere in the produced implementation guide

</body>
</html>

**Comment by ziegm** [comment]
How to do it, see here: https://github.com/hl7ch/ch-core/commit/6d10475f015024d6b6bb68dfa96e614d82e37630

**Comment by ralych** [comment]
change can be seen under [stu3-ballot_resolution](https://github.com/hl7ch/ch-vacd/tree/stu3-ballot_resolution)

**Comment by ziegm** [comment]
Maybe you could remove (some) entries from the copyright section, because they are duplicated now in the IP Statements section?
The rest looks good to me.

**Comment by pjolo** [comment]
Reviewed and ok
