### ISSUE TITLE
Error in testcase Bundle-A-D6-HCP1-C1.json

### ISSUE THREAD

**Issue by ch-fuchs** [hl7ch/ch-vacd#156]
The test file
http://fhir.ch/ig/ch-vacd/Bundle-A-D6-HCP1-C1.json.html
is not valid. 

Especially, there is no information about the validating practitioner _PractitionerRole/TC-HCP2-ORG2-ROLE-performer_

**Comment by ralych** [comment]
as in the QA report, there is no error in the bundle:
http://fhir.ch/ig/ch-vacd/qa.html#C__Users_micha_AppData_Local_Temp_ch.fhir.ig.ch-vacd_2.1.0_fsh-generated_resources_bundle-A-D6-HCP1-C1

it is referenced to the following resource:
http://fhir.ch/ig/ch-vacd/PractitionerRole-TC-HCP2-ORG2-ROLE-performer.html

**Comment by ralych** [comment]
this is automatically done using the generation with fsh and publisher.

**Comment by ch-fuchs** [comment]
The validator should be checked in that case.

Refering to the raw code:
ll. 399  "reference": "PractitionerRole/TC-HCP2-ORG2-ROLE-performer" which is the performer of the immunization.

The only practitionerRole definition (i.e. "resourceType": "PractitionerRole") in that bundle is the on in ll 315 following, which does refer "fullUrl": "http://test.fhir.ch/r4/PractitionerRole/TC-HCP1-ORG1-ROLE-author",

I would expect that there is a practitionerRole which refers the PractitionerRole/TC-HCP2-ORG2-ROLE-performer or am I missing something here?

**Comment by ralych** [comment]
@ch-fuchs: please verify if it is fixed now. see the ci-build of the branch: http://build.fhir.org/ig/hl7ch/ch-vacd/branches/stu3-ballot_resolution/index.html

**Comment by ch-fuchs** [comment]
Thanks for the fix, seems good now. Our project is going through the test cases in the next days. If we find anything, we will report it.
