### ISSUE TITLE
CH VACD Immunization.status (eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#160]
ch.fhir.ig.ch-vacd#2.1.0 /StructureDefinition-ch-vacd-immunization.html

Define new Valueset for Immunization.status (Vaccination done, Entered in error, Vaccination planned), came as userfeedback from healthcareprofessionals

eHealth Suisse

**Comment by ralych** [comment]
The resource Immunization ha other meaning, than documenting planned immunizatons.
see [Scope & Usage](http://hl7.org/fhir/R4/immunization.html#scope)

The new resource [ImmunizationEvaluation](http://hl7.org/fhir/R4/immunizationevaluation.html#scope) could be the correct one.
