### ISSUE TITLE
CH VACD AllergyIntolerance (eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#161]
ch.fhir.ig.ch-vacd#2.1.0 /StructureDefinition-ch-vacd-allergyintolerances.html

Remove must support from field type, there is no additional value from view of healthcareprofessional in the reaction valuelist it's clear what sort (allergy or intolerance) it is. Please also check with allergy CH format.

eHealth Suisse

**Comment by walterwellauer** [comment]
in order to change the Must support in CH-AllergyIntolerance we would either have to change it in IPS or release the dependency on ips:
dependencies:
  ch.fhir.ig.ch-core: 2.0.0
  hl7.fhir.uv.ips:
    version: 1.0.0
    uri: http://hl7.org/fhir/uv/ips/ImplementationGuide/hl7.fhir.uv.ips
    id: ips

**Comment by ralych** [comment]
Not solvable in this IG it will be closed
