### ISSUE TITLE
Must Support (Michaela Ziegler (ahdis ag))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#169]
ch.fhir.ig.ch-vacd#3.1.0 /

Provide a description of the flag Must Support in the context of CH VACD, like here: http://fhir.ch/ig/ch-emed/index.html#mustsupport

Michaela Ziegler (ahdis ag)

**Comment by pjolo** [comment]
I would change the link for "Impfen_MustSupprt" to the link https://www.fedlex.admin.ch/filestore/fedlex.data.admin.ch/eli/oce/2022/38/de/pdf-a/fedlex-data-admin-ch-eli-oce-2022-38-de-pdf-a.pdf#page=5

**Comment by ralych** [comment]
link ist angepasst

**Comment by ziegm** [comment]
Ich persönlich finde es mit dieser Erklärung immer noch relativ schwierig zu verstehen, was jetzt mit mustSupport gemeint ist (bin aber auch nicht tief im Austauschformat drin). Wäre diese Beschreibung (http://build.fhir.org/ig/hl7ch/ch-emed/index.html#meaning-of-the-flag-mustsupport-for-this-implementation-guide) zutreffend oder was ist abweichend.
