### ISSUE TITLE
ValueSet: ch-vacd-vaccines-vs add "Vaccine unknown"

### ISSUE THREAD

**Issue by pjolo** [hl7ch/ch-vacd#171]
The vaccination experts at the FOPH would like to include a term "Vaccine unknown" in the Value Set.

The following code should be included in the Value Set:

787859002 Unbekannter Impfstoff
787859002 Vaccine unknown
787859002 vaccin inconnu
787859002 vaccino sconosciuto
787859002 vaccin nunenconuschent

**Comment by ralych** [comment]
@pjolo is it ok to add it to the ValueSet ch-vacd-vaccines-snomedct-vs or should it also be added to the h-vacd-vaccines-vs?

**Comment by pjolo** [comment]
@ralych The code should also be added to the ValueSet ch-vacd-vaccines-vs
