### ISSUE TITLE
ch-vacd-risks-*-vs (Roeland Luykx /RALY GmbH))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#173]
ch.fhir.ig.ch-vacd#4.0.0-ballot /ValueSet-ch-vacd-risks-*-vs

Missing the SCT#373068000 "Undetermined (qualifier value)" in each valueset. It's only in the including valueset defined.

Roeland Luykx /RALY GmbH)

**Comment by ralych** [comment]
implemented
