### ISSUE TITLE
TC A 02: markdown instead of html (Oliver Egger (ahdis))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#176]
ch.fhir.ig.ch-vacd#4.0.0-ballot /TC_A02.html

[A-D4-HCP2-C2] (Bundle-A-D4-HCP2-C2.html) is not converted to a html link in the test description

Oliver Egger (ahdis)

**Comment by ralych** [comment]
this error cannot be reproduced

**Comment by pjolo** [comment]
I am closing the ticket as the error could not be reproduced.

**Comment by oliveregger** [comment]
<img width="430" alt="image" src="https://github.com/hl7ch/ch-vacd/assets/2414516/2279ad9f-5eae-417a-ac14-f951e72ea746">

https://fhir.ch/ig/ch-vacd/TC_A02.html

**Comment by oliveregger** [comment]
@pjolo @ralych can you see the issue above? [A-D4-HCP2-C2] (Bundle-A-D4-HCP2-C2.html)

**Comment by pjolo** [comment]
Changes are good
