### ISSUE TITLE
Use Case 1 Impfdokumentation Sichten (Oliver Egger (ahdis ag))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#177]
ch.fhir.ig.ch-vacd#4.0.0-ballot /Use-Case-1-Impfdokumentation-sichten.html

>fragt die Dokumente aus allen Stammgemeinschaften ab
sollte das nicht aus allen Gemeinschaften sein? es kann ja auch sein, dass eine Impfung für den Patient auch in einer Gemeinschaft dokumentiert wäre.

Oliver Egger (ahdis ag)

**Comment by pjolo** [comment]
Change are ok
