### ISSUE TITLE
Unprecise translation of SNOMED Code in value set Swiss Risks

### ISSUE THREAD

**Issue by eHealth-Suisse** [hl7ch/ch-vacd#182]
The value set Swiss Risks contains the code 373068000. This code was not discussed when the value sets were developed. I am not sure where it comes from. The translation of the code does not correspond to the meaning of the SNOMED code. --> The correct translation should be "Nicht bekannt" or "Unbekannt".

**Comment by pjolo** [comment]
@ralych 
I have discussed the problem with Pero. 
Your proposed translations will be included in the SNOMED Swiss Extension in June. Since the Swiss Extension is already freezed for the release

**Comment by ralych** [comment]
@pjolo This issue was already fixed in ballot 4. was labeled review-fix. But no review was done...
should be closed...

**Comment by pjolo** [comment]
The translation into Swiss Extension will be added in June. 
From my side the changes are good and I close the issue
