### ISSUE TITLE
Redundant codeSystem SwissAllergyIntoleranceCodesystem

### ISSUE THREAD

**Issue by eHealth-Suisse** [hl7ch/ch-vacd#184]
The CodeSystem SwissAllergyIntoleranceCodesystem appears redundant. It contains 4 codes based on the structure of SNOMED CT. Instead of creating a new codesystem, it would be better to submit these 4 codes as a change request to the National Release Center.

**Comment by ralych** [comment]
These codes where in discussion but never brought up for snomed ct registration or where rejected.
@PeroGrgic : what was the topic about them?

**Comment by pjolo** [comment]
I looked this issue with Pero. The four codes will be submitted as a change request to SNOMED International. Until then, this ticket will remain in the backlog.

**Comment by ralych** [comment]
@PeroGrgic 
is it correct that
1303852006 |Adverse reaction to component of vaccine product containing Human alphaherpesvirus 3 antigen (disorder)| --> combined code for varicella antigen & Herpes zoster since those are synonyms

replaces the two codes:
http://fhir.ch/ig/ch-vacd/CodeSystem/ch-vacd-allergyintolerance-cs#allergyvaccineherpeszoster
http://fhir.ch/ig/ch-vacd/CodeSystem/ch-vacd-allergyintolerance-cs#allergyvaccinevarizella
?
@PeroGrgic @pjolo : translation for DE,FR,IT,RM is needed.

**Comment by ralych** [comment]
[ci-build of branch](https://build.fhir.org/ig/hl7ch/ch-vacd/branches/184-redundant-codesystem-swissallergyintolerancecodesystem/ValueSet-ch-vacd-immunization-allergyintolerances-vs.html)

**Comment by ralych** [comment]
@pjolo still translation needed.

**Comment by pjolo** [comment]
@ralych The translations will be reviewed in the SNOMED groups and then I can give them to you

**Comment by pjolo** [comment]
@ralych: The missing translations:
Code| Deutsch|Englisch|Französisch|Italiensich|Räthoromanisch
-- | -- | -- | -- | -- | --
1303850003 |Unerwünschte Wirkung eines FSME-Impfstoffs|Adverse reaction to component of vaccine product containing Tick-borne encephalitis virus antigen | effet indésirable du vaccin contre la FSME | reazione avversa al vaccino contro la TBE | effect nungiavischà d'in vaccin FSME
1303851004 | Unerwünschte Wirkung eines Humanen-Papillomaviren-Impfstoffs | Adverse reaction to component of vaccine product containing Human papillomavirus antigen | effet indésirable du vaccin contre le papillomavirus humain | reazione   avversa al vaccino contro il papillomavirus umano | effect nungiavischà d'in vaccin da pirlas da l'uman
1303852006 | Unerwünschte Wirkung eines   Varizellen-Impfstoffs | Adverse reaction to   component of vaccine product containing Human alphaherpesvirus 3 antigen | effet indésirable du vaccin contre la varicelle | reazione avversa al vaccino contro la varicella | effect nungiavischà d'in vaccin cunter varizellas
700468006 |   |   |   |   | allergia cunter il   vaccin cunter Rotavirus
294657002 |   |   |   |   | allergia cunter in   vaccin en virola
294641002 |   |   |   |   | allergia cunter in   vaccin cunter antrax
39579001 |   |   |   |   | reacziun anafilactica

**Comment by ralych** [comment]
[ci-build](https://build.fhir.org/ig/hl7ch/ch-vacd/branches/184-redundant-codesystem-swissallergyintolerancecodesystem/index.html)

ValueSet: [ch-vacd-immunization-allergyintolerances-vs](https://build.fhir.org/ig/hl7ch/ch-vacd/branches/184-redundant-codesystem-swissallergyintolerancecodesystem/ValueSet-ch-vacd-immunization-allergyintolerances-vs.html)

**Comment by pjolo** [comment]
The adaptations are good
