### ISSUE TITLE
fixedValue for coding.display (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#185]
Best practice for patternCodeableConcept would be to set a fixedValue for code and system, not for display.
See an example in CH EMED: http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-composition-medicationlist.html

Michaela Ziegler, ahdis ag

**Comment by ziegm** [comment]
@ralych Kann ich etwas reviewen? Wenn ja, was/wo?

**Comment by ralych** [comment]
http://build.fhir.org/ig/hl7ch/ch-vacd/StructureDefinition-ch-vacd-composition-immunization-administration.html
http://build.fhir.org/ig/hl7ch/ch-vacd/StructureDefinition-ch-vacd-composition-vaccination-record.html
and whatever you have seen opening the ticket.

**Comment by ziegm** [comment]
thanks, it's good, you can close the issue
