### ISSUE TITLE
TC A 03 (Oliver Egger, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#187]
ch.fhir.ig.ch-vacd#4.0.0-ballot /TC_A03.html

PAT2023 discussion:
- Create document Vaccination Record is misleading, this is only done by a patient
- According to the discussion, there is no relation between the docs, "Dok5 refers to the vaccination entry in Dok3" would not be correct

Oliver Egger, ahdis ag

**Comment by ralych** [comment]
The diagram will be changed to be more clear

**Comment by ralych** [comment]
There is no reference for a second dose.
inter document and element refrences are only used if there are updates of attributes of an entry

**Comment by pjolo** [comment]
Changes are good
