### ISSUE TITLE
Clarification regarding Cross Reference (Marco Studer, Cistec AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#192]
ch.fhir.ig.ch-vacd#4.0.0-ballot /StructureDefinition-ch-vacd-ext-cross-reference.html

The document/entry valueReferences aren't clearly defined in my opinion. The test case examples suggest to use the ID element. The bundles exchanged during the Projectathon testing showed that the vendors are using the identifier.value element. Which approach is correct?

Marco Studer, Cistec AG

**Comment by ralych** [comment]
see: http://fhir.ch/ig/ch-emed/StructureDefinition-ch-emed-ext-treatmentplan.html

**Comment by ralych** [comment]
Work is done
