### ISSUE TITLE
CH VACD Message Immunization Recommendation Request (Aline Andres, HCI Solutions AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#193]
ch.fhir.ig.ch-vacd#4.0.0-ballot /StructureDefinition-ch-vacd-recommendation-request-message.html

In the ch-vacd-recommendation-request-message bundle, it is specified that a patient is mandatory. Reference is made to the CH Core Patient Resource, where only the identifier is specified as a mandatory field. For the CDS request, however, we absolutely need a first name, a name, date of birth and the gender. In our opinion, this information should also be defined as mandatory fields.

Aline Andres, HCI Solutions AG

**Comment by ralych** [comment]
With the defined profile, the name.family name.given is required by constraint.
The gender, birthdate are note required
Proposal is to use the CH Core Patient EPR

**Comment by pjolo** [comment]
Change are ok
