### ISSUE TITLE
Missing Allergy against rotavirus antigen vaccine product (700468006	Allergy to component of vaccine product containing Rotavirus antigen (finding))

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#196]
ch.fhir.ig.ch-vacd#4.0.0-ballot /

During the projectathon 2023 we noticed that one value is missing in the following value set and should be added:
http://fhir.ch/ig/ch-vacd/ValueSet-ch-vacd-immunization-allergyintolerances-vs.html
700468006 Allergy to component of vaccine product containing Rotavirus antigen (finding)

700468006	Allergy to component of vaccine product containing Rotavirus antigen (finding)

**Comment by pjolo** [comment]
Good
