### ISSUE TITLE
Missing Allergies in Valueset / resolving redundance with CH-AllergyIntolerance (Daniel Ratschiller, CISTEC AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#197]
CH-VACD

During the projectathon, we noticed that there are allergies to vaccination products in the CDS of HCI that are not fully present in the allergy value set of vaccination products (ch-vacd-immunization-allergyintolerances-vs). Some gaps could be closed here in a comparison work. E.g. monkey protein allergy CHA-116 seems to be a missing entitity in the vaccination products Rotarix, Boostrix Polio, Infanrix hexa...
And would it not be generally welcome to resolve the given redundancy problem of the corresponding value set in CH-VACD and CH-AllergyIntolerance in a future release by merging them somehow?

Daniel Ratschiller, CISTEC AG

**Comment by ralych** [comment]
According to the merging of the valuesets of ch-vacd and allergyintollerance see comments in #183

**Comment by ralych** [comment]
mokey protein allergy seems to be a problem in past times. see https://www.jacionline.org/article/0021-8707(57)90131-4/fulltext
from the 1950s

**Comment by pjolo** [comment]
good
