### ISSUE TITLE
ch-vacd-risks-medical-vs (Gabriel Hess, I4MI BFH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#206]
ch.fhir.ig.ch-vacd#4.0.0-ballot /ValueSet-ch-vacd-risks-medical-vs.html

Typo bei "26034001 Konsument / Kunsumentin von injizierbaren Drogen": Konsumentin statt Kunsumentin

Gabriel Hess, I4MI BFH

**Comment by pjolo** [comment]
The changes are good
