### ISSUE TITLE
2.1 Composition Immunization Administration - JSON Representation ( Carole Kaiser eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#207]
ch.fhir.ig.ch-vacd#4.0.1 /Composition-2-1-ImmunizationAdministrationComposition.json.html

Im
"type" : {
    "coding" : [
      {
        "system" : "http://snomed.info/sct",
        "code" : "41000179103",
        "display" : "Immunization record"
      }
    ]
Wird von Immunization record gesprochen und später ist es dann ein "title" : "Immunization Administration", stimmt das so? oder sollte es nicht ein Immunization Administration sein?

 Carole Kaiser eHealth Suisse

**Comment by pjolo** [comment]
Dies ist so korrekt, da der type code dem DocumentEntry.typeCode gemäss Anhang 3 EPDV-EDI entspricht. Für Impfungen ist nach Anhang 3 der Code 41000179103 Immunization record (record artifact) definiert.
