### ISSUE TITLE
Bexsero vaccine missing in concept-map

### ISSUE THREAD

**Issue by Antechronos** [hl7ch/ch-vacd#208]
Hello,
We are using the swissmedic codes value-set and the "Bexsero" vaccine is indeed defined there:
https://fhir.ch/ig/ch-vacd/ValueSet-ch-vacd-vaccines-vs.json.html

However is seems to be missing from both the "TargetDisease To VaccineCode" and "VaccineCode To TargetDisease" concept maps:
https://fhir.ch/ig/ch-vacd/ConceptMap-ch-vacd-targetdiseases-vaccines-cm.json.html
https://fhir.ch/ig/ch-vacd/ConceptMap-ch-vacd-vaccines-targetdiseases-cm.json.html

Swissmedic reference:
https://www.swissmedic.ch/swissmedic/en/home/humanarzneimittel/authorisations/new-medicines/bexsero-injektionssuspension.html

Kind regards

**Comment by pjolo** [comment]
The changes are good
