### ISSUE TITLE
Changes according to EKIF 2024

### ISSUE THREAD

**Issue by ralych** [hl7ch/ch-vacd#210]

**Comment by ralych** [comment]
There will be no effekt on structural things. There will be additional entries on codesystems and valuesets

**Comment by ralych** [comment]
Code Change 
Alter code (bleibt aus redundanzgründen bestehen)
72291000195105 ¦ Residence or stay in Switzerland except Geneva and Ticino (finding)
Neuer zusätzlicher code 
102311000195108 | Residence or stay in Switzerland except Ticino (finding)

![image](https://github.com/hl7ch/ch-vacd/assets/75606442/80b952be-a7b6-49c1-a0c9-639fb65bf41a)

**Comment by ralych** [comment]
[ci-build](https://build.fhir.org/ig/hl7ch/ch-vacd/branches/210-changes-according-to-ekif-2024/index.html)

**Comment by pjolo** [comment]
The adaptation is good
