### ISSUE TITLE
Adapt example "1.1 Immunisation Administration"

### ISSUE THREAD

**Issue by pjolo** [hl7ch/ch-vacd#213]
ch.fhir.ig.ch-vacd#4.0.1 /Bundle-1-1-ImmunizationAdministration.json.html

The example should be adapted. For Bundle.entry:Practitioner, Bundle.entry:PractitionerRole and Bundle.entry:Organization, the profiles http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-practitioner, http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-practitionerrole and http://fhir.ch/ig/ch-core/StructureDefinition/ch-core-organization should should be used similar to the example from CH EMED: https://fhir.ch/ig/ch-emed/Bundle-2-7-MedicationCard.json.html

The same changes should also be made for the example https://fhir.ch/ig/ch-vacd/Bundle-1-3-VaccinationRecord.json.html.

**Comment by ralych** [comment]
@pjolo this is in my opinion not correct. the [composition](http://fhir.ch/ig/ch-vacd/StructureDefinition-ch-vacd-composition-immunization-administration.html) is derived from [CompositionEPR](http://fhir.ch/ig/ch-core/4.0.1/StructureDefinition-ch-core-composition-epr.html). And for the Composition.subject, Composition.author und Composition.section.author are pointing on the corresponding EPR profiles.
It is correct that the entries i.e. Immunization.patient, Immunization.performer are pointing to the not EPR profiles. But it is not wrong to take an EPR profile Patient resource as reference.
