### ISSUE TITLE
New KSW request for basic immunization

### ISSUE THREAD

**Issue by pjolo** [hl7ch/ch-vacd#229]
Lieber Roeland und Patrick
 
Wir haben vom Spital Winterthur eine spannende Anfrage erhalten, über die wir vielleicht mal bei Bedarf per Zoom diskutieren könnten?
 
Offensichtlich haben wir ja unter den artifacts dieses [CH VACD Basic Immunization](https://fhir.ch/ig/ch-vacd/StructureDefinition-ch-vacd-basic-immunization.html) mit dem Hinweis, dass dies als condition dient für die Deklaration der Grundimmunisierung durch eine einzige condition für DTPa oder Polio. 
Dies gelte für den Fall, dass der Patient keinen Impfnachweis habe, um dies anzumelden, aber wisse, dass dies der Fall sei, vgl. https://fhir.ch/ig/ch-vacd/StructureDefinition-ch-vacd-basic-immunization.html
 
Im KSW wollen sie nun sozusagen für alle Krankheiten so eine Checkbox, damit sie jeweils sagen können «an dem Datum war der Impfschutz vollständig», ohne minuziös alle Details ausfüllen zu müssen.
 
Gibt es Gründe, warum dies hier nur für DTPa und Polio vorgesehen wurde, oder könnte man das entsprechend erweitern für die Liste unten?
 
LG Daniel
 
Daniel Ratschiller
Dr. med. EMBA FH | Productmanagement

**Comment by pjolo** [comment]
hallo zusammen

dies hat glaube ich mit dem impfplan vom EKIF und der umsetzung des CDS zu tun. ich glaube das hatten wir bereits mein meineimpfungen drin und beim umsetzten des impfchecks von HCI ist das thema wieder aufgepoppt.
ich denke das könnte man schon erweitern. müssten wir evtl. mal in einer AG ch-vacd telco zusammen mit lisa diskutieren.

gruss roeland

**Comment by pjolo** [comment]
Hallo Roeland

Ah, spannender Hinweis, dann kam das wohl von dort her in den Implementation Guide CH VACD, https://fhir.ch/ig/ch-vacd/index.html 

Ich finde die dazu passende Stelle im Impf-Fragebogen der HCI, vgl. Screenshot, dort wohl auch in der Idee, die Dokumentation etwas abkürzen zu können.

Vac CDS: https://pharmavista.ch/vaccination und EFIK: https://www.infovac.ch/de/impfungen/schweizerischer-impfplan

Habt ihr bereits einen nächsten Telco-Termin geplant, wo wir das KSW-Anliegen diskutieren könnten?

LG Daniel

![image](https://github.com/hl7ch/ch-vacd/assets/87263053/774d1b78-6a54-4d04-9a95-846a9b457be8)

**Comment by ralych** [comment]
There is nothing speaking against an extension of the codesystem/valueset to other vaccines.
The already required date in the Condition resource does receive an other meaning depending on the vaccination and the vaccination plan behind.
The meaning of the Codes should be clear!


Outcome from WG VACD 25.3.24

**Comment by ralych** [comment]
Proposal done. See [CS_BasicImmunization_Texts%3A20240411.xlsx](https://github.com/hl7ch/ch-vacd/blob/229-new-ksw-request-for-basic-immunization/doc/CS_BasicImmunization_Texts%3A20240411.xlsx)

**Comment by ralych** [comment]
@pjolo please let translate the texts to the different languages

**Comment by pjolo** [comment]
I have already sent the texts to the translation service and should be done next week

**Comment by pjolo** [comment]
@ralych : The table shows the translations:

Deutsch | Französisch | Italiensich
-- | -- | --
Grundimmunisierung   gegen DTPa in der Kindheit erhalten | Vaccination de base contre le   DTPa effectuée durant l’enfance | Completamento   dell’immunizzazione di base contro DTPa durante l’infanzia
Grundimmunisierung   gegen Poliomyelitis in der Kindheit erhalten | Vaccination de base contre la   poliomyélite effectuée durant l’enfance | Completamento   dell’immunizzazione di base contro la poliomielite durante l’infanzia
Grundimmunisierung   gegen die Frühsommer-Meningoenzephalitis erhalten | Vaccination de base contre la   méningo-encéphalite verno-estivale effectuée | Completamento   dell’immunizzazione di base contro la meningoencefalite verno-estiva
Grundimmunisierung   gegen Hämophilus influenzae Typ b erhalten | Vaccination de base contre   l’Haemophilus influenzae de type b effectuée | Completamento   dell’immunizzazione di base contro l’Haemophilus influenzae di tipo b
Grundimmunisierung   gegen Humanes Papillomavirus erhalten | Vaccination de base contre le   papillomavirus humain effectuée | Completamento   dell’immunizzazione di base contro i papillomavirus umani
Grundimmunisierung   gegen Windpocken erhalten | Vaccination de base contre la varicelle effectuée | Completamento   dell’immunizzazione di base contro la varicella
Grundimmunisierung   gegen Masern, Mumps, Röteln erhalten | Vaccination de base contre la   rougeole, les oreillons et la rubéole effectuée | Completamento   dell’immunizzazione di base contro morbillo, orecchioni e rosolia
Grundimmunisierung   gegen Pneumokokken-Erkrankung erhalten | Vaccination de base contre la   maladie à pneumocoques effectuée | Completamento   dell’immunizzazione di base contro la malattia invasiva da pneumococchi
Grundimmunisierung   gegen virale Hepatitis Typ B erhalten | Vaccination de base contre l’hépatite virale de type B | Completamento   dell’immunizzazione di base contro l’epatite virale B
Grundimmunisierung   gegen virale Hepatitis Typ A erhalten | Vaccination de base contre l’hépatite virale de type A   effectuée | Completamento   dell’immunizzazione di base contro l’epatite virale A
Grundimmunisierung   gegen Herpes zoster erhalten. | Vaccination de base contre   l’herpès zoster effectuée | Completamento   dell’immunizzazione di base contro l’herpes zoster
Grundimmunisierung   gegen Meningokokken-Erkrankung erhalten | Vaccination de base contre la   maladie à méningocoque effectuée | Completamento   dell’immunizzazione di base contro la malattia invasiva da meningococchi
Grundimmunisierung   gegen Tollwut erhalten | Vaccination de base contre la   rage effectuée | Completamento   dell’immunizzazione di base contro la rabbia

**Comment by pjolo** [comment]
Good
