### ISSUE TITLE
Spelling CH VACD (vs. CH-VACD) (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#233]
ch.fhir.ig.ch-vacd#4.0.1 /

Unify spelling according to the title CH VACD:
- e.g. on Home: The CH-VACD implementation guide ...
- maybe at other places?

Michaela Ziegler, ahdis ag

**Comment by ralych** [comment]
@ziegm please review and set label from review-fix to ready-2-merge if ok.
