### ISSUE TITLE
Dependency IPS (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#234]
ch.fhir.ig.ch-vacd#5.0.0-ci-build /

Can you use the newest publication v1.1.0 of IPS instead of v1.0.0?
https://hl7.org/fhir/uv/ips/history.html

Michaela Ziegler, ahdis ag

**Comment by ralych** [comment]
@ziegm please review and set label fom review-fix to ready-2-merge if ok
