### ISSUE TITLE
Use Cases Deutsch: div. typos (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#235]
ch.fhir.ig.ch-vacd#5.0.0-ci-build /Use-Cases-Deutsch.html

Please review the hole page concerning typos

Michaela Ziegler, ahdis ag

**Comment by ralych** [comment]
@ziegm please review and set label from review-fix to ready-2-merge if ok.
[ci-build](https://build.fhir.org/ig/hl7ch/ch-vacd/branches/235-use-cases-deutsch-div-typos-michaela-ziegler-ahdis-ag/index.html)
