### ISSUE TITLE
ValueSet "Swiss Occupation Risks For Immunizations" 

### ISSUE THREAD

**Issue by pjolo** [hl7ch/ch-vacd#246]
There is a new risk group for the influenza recommendation 

New SNOMED codes have been created for the new risk group  

- 1342377006 Has contact with wild bird (situation)
- 1342378001 Has contact with poultry bird (situation)

The translations are still in progress

These codes should be included in the Value Set "Swiss Occupation Risks For Immunizations"

**Comment by ralych** [comment]
should be done in https://github.com/hl7ch/ch-term/

**Comment by ralych** [comment]
@pjolo solle das nicht in "Swiss Social Risks For Immunizations" sein. dort haben wir werte mit _situation_ drin. unter Swiss Occupation Risks For Immunizations sind nur werte mit _occupation_ drin

**Comment by pjolo** [comment]
@ralych 
Wenn ich das Mail von Lisa lese, geht es um Personen mit **regelmässigem** oder **beruflichen** Kontakt: 
![image](https://github.com/user-attachments/assets/a25d3f98-3cd7-4490-b775-826d0b5d3859)
Theoretisch würde es in beiden passen. Aber wir können es gut in "Swiss Social Risks For Immunizations" einfügen

**Comment by ralych** [comment]
@pjolo translation missing
