### ISSUE TITLE
New Pneumococcal vaccine  - Prevenar 20

### ISSUE THREAD

**Issue by pjolo** [hl7ch/ch-vacd#247]
There is a new vaccine for Pneumococcal which has been approved by Swissmedic.

- 69222 Prevenar 20, Injektionssuspension in einer Fertigspritze

This vaccination should be included in the code system [CH VACD Swissmedic Authorised Vaccines](https://fhir.ch/ig/ch-term/CodeSystem-ch-vacd-swissmedic-cs.html) and in the value set ‘[CH VACD Swissmedic code for vaccine code](https://fhir.ch/ig/ch-term/ValueSet-ch-vacd-vaccines-vs.html)’.
The concept maps [Snomed CT VaccineCode To SwissMedic VaccineCode](https://fhir.ch/ig/ch-term/ConceptMap-ch-vacd-vaccines-sct-sm-cm.html), [SwissMedic VaccineCode To Snomed CT VaccineCode](https://fhir.ch/ig/ch-term/ConceptMap-ch-vacd-vaccines-sm-sct-cm.html) and [VaccineCode To TargetDisease Mapping](https://fhir.ch/ig/ch-term/ConceptMap-ch-vacd-vaccines-targetdiseases-cm.html) must also be changed.

**Comment by pjolo** [comment]
Swissmedic has approved a dengue vaccine. This should also be included in the value sets, etc.

**Comment by ralych** [comment]
Will be handled in https://github.com/hl7ch/ch-term/issues/38

**Comment by ralych** [comment]
see https://github.com/hl7ch/ch-term/pull/50
