### ISSUE TITLE
Covid (new recommendation for autumn 2024)

### ISSUE THREAD

**Issue by pjolo** [hl7ch/ch-vacd#248]
The Snomed Code 870577009 At increased risk of exposure to severe acute respiratory syndrome coronavirus 2 (finding) must be included in the Value Set [Swiss Risks For Immunisations](http://fhir.ch/ig/ch-vacd/ValueSet-ch-vacd-risks-vs.html)

**Comment by ralych** [comment]
has to be added to the sub valueset: [Swiss Medical Risks For Immunizations](http://fhir.ch/ig/ch-vacd/ValueSet-ch-vacd-risks-medical-vs.html)

**Comment by ralych** [comment]
@pjolo translation missing
