### ISSUE TITLE
CH VACD Immunization Administration Composition (Gabriel Hess, BFH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#250]
ch.fhir.ig.ch-vacd#5.0.0-ballot /StructureDefinition-ch-vacd-composition-immunization-administration.html

Allow "entered-in-error" as status.

I encountered an use case in the Impfmodul implementation used in the Sanela EPD, where the fixed status could be a problem:

When editing or deleting a Immunization Administration Composition, a new resource is created. This new resource has a reference to the old one it replaces, but the old resource is not changed at all. Because of this the old resource still has the status „final“ (as it is fixed in the IG).
When, for some reason, only the old document is processed, there is no hint that this Immunization Administration document is not valid anymore; which can lead to misunderstandings.
Allowing „entered-in-error“ as status for the CH VACD Immunization Administration Composition would prevent this.

Gabriel Hess, BFH

**Comment by ralych** [comment]
In context  to the document is it final on the date it is created. if there are changes to fix errors an new document will be created with the corresponding realtesTo and other extensions to fix the error in the old document.
But on time the document is created its final and will not be changed anymore.

**Comment by heg2** [comment]
Of course nobody wants to create a document with the status "entered-in-error".  With your argumentation, the existence of "entered-in-error" as part of the status valueset in FHIR would be obsolete in general.

But errors do happen, and if they do we should have a possibility to mark a document as not valid; and as long we can't absolutely make sure the recieving system also processes the second, corrected document with the "relatedTo", not marking the first document as invalid in some way or another can lead to misinterpretation.

Also, as far as I see, the status is not fixed on "final" in other CH IGs, but I don't see why the vaccination usecase differs here to have an inconsistency.

**Comment by pjolo** [comment]
This issue was discussed at the meeting on 11.11.2024.
The "entered-in-error" status cannot be used in the context of the EPR, as the documents can only be read and not written via Cross Community. This means that the “entered-in-error” status cannot be set for the document with the error.
If there is an error in a document, a new document is created and referenced with relatesTo to the old document that is no longer valid.
