### ISSUE TITLE
10.3 ImmunizationRecommendation (Recommendation Request/Response) (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#258]
ch.fhir.ig.ch-vacd#5.0.0-ci-build /ImmunizationRecommendation-10-3-ImmunizationRecommendation.html

vaccineCode: Influenza vaccination
targetDisease is not: Cholera (disorder), but Influenza

Marcel Hanselmann

**Comment by ralych** [comment]
see ci-build: https://build.fhir.org/ig/hl7ch/ch-vacd/branches/258-103-immunizationrecommendation-recommendation-requestresponse-marcel-hanselmann/index.html
