### ISSUE TITLE
1.3 Vaccination Record (Marcel Hanselmann)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#259]
ch.fhir.ig.ch-vacd#5.0.0-ci-build /Bundle-1-3-VaccinationRecord.html

Propose to use GTIN as identifier of Vaccine Product (e.g. Boostrix)

Marcel Hanselmann

**Comment by ralych** [comment]
This is a returning issue already discusse earlier. here the reason why not and where the GTIN can be placed:

The GTIN is identifiing the product and its pacakge. there may exists multiple GTIN for the same thing.
Therefor we have an extension defined to reference a Medication resource where the GTIN can be set.

The swissmedic code from the swissmedic codesystem and from the corresponding valueset is a part of the GTIN and identifies the accreditated vaccine product.
