### ISSUE TITLE
Immunization Administration Document - typos (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#262]
ch.fhir.ig.ch-vacd#5.0.0-ballot /immunization-administration-document.html

. for further details see Narrative Text Generation
-> For
-> missing point at the end

Michaela Ziegler, ahdis ag

**Comment by ralych** [comment]
see ci build: https://build.fhir.org/ig/hl7ch/ch-vacd/branches/262-immunization-administration-document-typos-michaela-ziegler-ahdis-ag/index.html

**Comment by ziegm** [comment]
Perfect, thanks!
