### ISSUE TITLE
Immunization Recommendation Request Message, linebreaks (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#263]
ch.fhir.ig.ch-vacd#5.0.0-ballot /immunization-recommendation-request-message.html

Is this line break as it should be?
Recommendation Request      
containing all relevant 

Michaela Ziegler, ahdis ag

**Comment by ralych** [comment]
See ci-build: https://build.fhir.org/ig/hl7ch/ch-term/branches/58-update-vaccines-csvscm-with-augustseptember-2024-vaccines/index.html

**Comment by ralych** [comment]
see ci-build: https://build.fhir.org/ig/hl7ch/ch-vacd/branches/263-immunization-recommendation-request-message-michaela-ziegler-ahdis-ag/index.html

**Comment by ziegm** [comment]
all good, thank you!
