### ISSUE TITLE
Immunization Recommendation Response Message (Stefan Csomor, Advanced Concepts AG)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#266]
ch.fhir.ig.ch-vacd#5.0.0-ballot /immunization-recommendation-response-message.html

not really relevant regarding the ballot content, just a detail in Examples 10.3:, perhaps I'm just not getting it, is an influenca vaccine really recommended against / for patients having ? cholera

Stefan Csomor, Advanced Concepts AG

**Comment by ralych** [comment]
duplicate of #258
