### ISSUE TITLE
CH VACD Immunization (Oleksiy CDM)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#292]
ch.fhir.ig.ch-vacd#5.0.0-ballot /StructureDefinition-ch-vacd-immunization.html

In this resource there is a statement "Definition of the immunization part for all documents, except recommendation request and response documents". However, CH VACD Message Immunization Recommendation Request has a reference to CH VACD Immunization. Can you clarify how to understand such a statment?

Oleksiy CDM

**Comment by ralych** [comment]
@Oleksiy yes thats not correct. Earlier there where 2 different profiles for immunization. one for documentation and one for recommendation request/response. will be changed.
thanks for the input
