### ISSUE TITLE
Revision of the code systems (Daniel Ratschiller, CISTEC AG)

### ISSUE THREAD

**Issue by drats-cis** [hl7ch/ch-vacd#52]
I would recommend revising the presentation and translations of the two code systems, remove CAPS-LOCK mode and _:
- Swiss Complication Risks Code System
- Swiss Exposure Risks Code System

Suggestion for the former: As it often deals with disorders, why not develop a code system with Snomed CT codes, e.g. 19943007 | Cirrhosis of liver (disorder) |?

**Comment by ralych** [comment]
This code systems are transformed from art-decor

- [Swiss Complication Risks Code System](https://art-decor.org/art-decor/decor-valuesets--cdachvacd-?id=2.16.756.5.30.1.1.11.72&effectiveDate=)
- [Swiss Exposure Risks Code System](https://art-decor.org/art-decor/decor-valuesets--cdachvacd-?id=2.16.756.5.30.1.1.11.73&effectiveDate=2018-04-19T00:00:00)

**Comment by ralych** [comment]
#56

**Comment by eHealth-Suisse** [comment]
the two risk value sets were combined in one. review of codesystem used and replacement with SNOMED CT codes is desireable, however we need some information on impact on CDS systems first. discussions ongoing. just to change the displayNames in the meantime has little use if probably whole VS will be adapted.
@drats-cis for information and potential objections

**Comment by ralych** [comment]
according to the lack of an coordination with an CDSS the actual codesystems and valueset stay as is. a new valueset based on snomedct exists as draft.
the issue will stay in the backlog.

**Comment by annatinafoppa** [comment]
This should be revised with the next version. Pero Grgic has made the necessary work together with HCI and SNOMED international. @PeroGrgic Please provide revised list as soon as it is ready
