### ISSUE TITLE
Provide Use Cases in IG (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#71]
ch.fhir.ig.ch-vacd#1.0.0 /

Add Use Cases according to eHealth Suisse vaccination concept in Implementation Guide. Which ones exactly is tbd.

Annatina Foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
- französische Übersetzung ergänzen
- CDA-Use-Cases veraltet, entfernen

**Comment by ralych** [comment]
Todo:
- remove CDA part from document
- Add EPR in french

**Comment by eHealth-Suisse** [comment]
Merci beaucoup
