### ISSUE TITLE
Typos and a very detail (Michaela Ziegler, ahdis ag)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#77]
ch.fhir.ig.ch-vacd#1.0.0 /immunization-administration-document.html

- in all -document.html: next tu the
- the numbering of the examples for the documents does not match the numbering of the title ;-)

Michaela Ziegler, ahdis ag

**Comment by ralych** [comment]
use this issue also for reviewing all text's

**Comment by eHealth-Suisse** [comment]
typos corrected, texts reviewed
issue creator @ziegm for information and potential objection

**Comment by ziegm** [comment]
> * next tu the
should it not be **next to the** ?

**Comment by eHealth-Suisse** [comment]
yes, but it should have been replaced everywhere ... where do you still see the "tu"?

**Comment by ziegm** [comment]
https://github.com/hl7ch/ch-vacd/search?q=tu

**Comment by eHealth-Suisse** [comment]
oh. merci, hatte das übersehen. @ralych kannst du das anpassen? und bei dieser gelegenheit auch gleich das "dataexchange" kurz vorher zu "data exchange" wechseln?

**Comment by ralych** [comment]
its done
