### ISSUE TITLE
Target disease and illnesses undergone for immunization, falsche Übersetzung rm für Windpocken (Roeland Luykx, RALY GmbH)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#78]
ch.fhir.ig.ch-vacd#1.0.0 /ValueSet-ch-vacd-targetdiseasesandillnessesundergoneforimmunization-vs.html

Code 38907003|Varicella (disorder) has wrong rm translation

Roeland Luykx (RALY GmbH)

**Comment by eHealth-Suisse** [comment]
die Übersetzung ist zwar korrekt, aber wir brauchen für das rm-valueset ja generell die deutschen Terme

**Comment by eHealth-Suisse** [comment]
@ralych ist immer noch der romanische Term drin, müsste "Windpocken" sein (weil wir nur DE brauchen). Kannst jetzt korrigieren oder beim Einkopieren der Übersetzungen. Schliesse dieses Ticket trotzdem, da das andere mit den Übersetzungen Value Sets noch offen ist.
