### ISSUE TITLE
ValueSet missing information COVID test Laboratory Serology for Immunization (eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#84]
ch.fhir.ig.ch-vacd#1.0.0 /ValueSet-ch-vacd-laboratory-serology-vs.html

Please check the valueSet Laboratory Serology for Immunization I could not find any information about coding a positive testresult for COVID. There could also be other tests missing.

eHealth Suisse

**Comment by ralych** [comment]
Which are the correct loinc codes for the valueset to be completed?
https://loinc.org/sars-cov-2-and-covid-19/

@eHealthSuisse: who to ask? ref labor in geneva?

**Comment by ralych** [comment]
The valueset to be completed: http://fhir.ch/ig/ch-vacd/ValueSet-ch-vacd-laboratory-serology-vs.html

**Comment by eHealth-Suisse** [comment]
Code for rabies and Covid added; Mumps deleted (because mumps virus IgG Ab in serum is NOT a reliable marker of protection against mumps). advised by Prof. Dr. Siegrist
