### ISSUE TITLE
Reactions to immunizations (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#86]
ch.fhir.ig.ch-vacd#1.0.0 /ValueSet-ch-vacd-immunization-allergyintolerances-vs.html

this was brought up as a potential future use case to be brought into the immunization certificate as well. a possible extension?

Annatina Foppa, eHealth Suisse

**Comment by eHealth-Suisse** [comment]
covered by the Allergy value set with "adverse reactions"
