### ISSUE TITLE
Usecase from hospital environment to report vaccination documentation to authorities (Daniel Ratschiller, Cistec AG)

### ISSUE THREAD

**Issue by drats-cis** [hl7ch/ch-vacd#88]
Input: Consider the possibility of reporting the following 3 G information (vaccination status, test status, disease status according to HIS input mask) to cantonal or federal authorities via FHIR exchange format?

![image](https://user-images.githubusercontent.com/80474467/134505494-8c0e5725-9c49-43c1-a771-46a5de20a6cc.png)

Daniel Ratschiller, Cistec AG

**Comment by eHealth-Suisse** [comment]
Remains on backlog for further enhancements, will therefore be kept open.
Issue creator @drats-cis for information and potential objection.

**Comment by ralych** [comment]
Spezielles Austauschformat für die Meldung an eine kantonale Stelle. Die Bedarf eher eines eigenen IG da mehr Themen betroffen sind als in Bezug aufs Impfen.
