### ISSUE TITLE
Check if Recommandations should be in the document -- Vaccination Record document (Annatina Foppa, eHealth Suisse)

### ISSUE THREAD

**Issue by ig-feedback** [hl7ch/ch-vacd#93]
ch.fhir.ig.ch-vacd#1.0.0 /vaccination-record-document.html

Recommandations are made at a specific point in time, should they be made persistent in document form or not documented in the EPR / document? to be discussed

Annatina Foppa, eHealth Suisse

**Comment by ralych** [comment]
see also issue #9 (already closed from informative ballot)

**Comment by oliveregger** [comment]
Gemäss Roeland Sections nicht relevant für ImmunizationRequest und Response
"Einfachste Variante": Bundle Collection or Message? -> äquivalent via CDS Hooks mit Prefetch aufbauen (CDS Hooks Container), separate Profildefinition unabhänging von CDS Hooks welche Daten angeben werden können

**Comment by ralych** [comment]
Immunization recommendation section is removed - recommendations should not be stored in vaccinationrecords
For Recommendation Request and Response new structure is defined.

**Comment by eHealth-Suisse** [comment]
discussion 14.1.:
optionally, the request message should be added to the response
