### ISSUE TITLE
add «extension:cross-reference» according to detail concept

### ISSUE THREAD

**Issue by eHealth-Suisse** [hl7ch/ch-vacd#95]
in order that a link between related documents can be provided.

**Comment by eHealth-Suisse** [comment]
@ralych Three comments to the extension http://build.fhir.org/ig/ehealthsuisse/ch-vacd/StructureDefinition-ch-vacd-ext-cross-reference.html :

-  CH VACD Immunization Recommendations Profile | schould not be a valid Reference on extension:entry since it is not a section of the documents anymore
- why is the extension not used on the composition level as well? in order to replace a whole document
- for Vaccination Record, you can only replace the whole document and not a single entry (entries have always to be replaced on Immunization Administration level, see concept), in which case the 1..1 requirement for extension:entry is too strong

**Comment by ralych** [comment]
lets see:

- Correct - recommendation profile has to be removed.
- on composition level we have already the relatesTo  property in the resource to declare the replacement
- thats a good point, but in respect to the point above its not relevant.

**Comment by eHealth-Suisse** [comment]
discussed 14.1.:
point 3: in consequence, remove "Vaccination record" from extension

**Comment by eHealth-Suisse** [comment]
thanks, ok
