### ISSUE TITLE
Expert review of valuesets and translations

### ISSUE THREAD

**Issue by ralych** [hl7ch/ch-vacd#99]
A review is done by experts for validation of the used valuesets and concept maps including tranlations.

**Comment by ralych** [comment]
valuesets and conceptmap are changed according to the feedback from expert side.

**Comment by ralych** [comment]
some translations missing

**Comment by annatinafoppa** [comment]
was done in January 2022. some translations are still reviewed by the SNOMED translation groups (French and German, coordination @PeroGrgic ) before being introduced in the Swiss Extension
